### PR TITLE
additional fix for laravel 6 support

### PR DESCRIPTION
**Pull request by dominik-wbz**

### CODE REVIEW

**Comment by marcreichel** [comment]
Please review your changes so not the whole file is marked as changed.
This repository is using 4 spaces instead of tabulator.

**Comment by dominik-wbz** [comment]
Alright, should be fine now.

**Comment by marcreichel** [comment]
Thanks man :) Damn :D Missed that snake case helper

**Comment by marcreichel** [comment]
v0.10.2 is released

**Pull request merged**
