### PR TITLE
✨ Add Support for Laravel 9

### PR DESCRIPTION
**Pull request by marcreichel**

### CODE REVIEW

**Comment by HDVinnie** [comment]
Are you waiting for Laravel 9 to release? Or could merge now for us on dev.

**Comment by marcreichel** [comment]
@HDVinnie Yeah, I thought I'd like to wait for Laravel to be released (so the test suite could  run through properly as well).

But I think there should not be any breaking changes. So I may merge it already. What is your opinion on this?

**Comment by HDVinnie** [comment]
From the release notes I see nothing that would break in this package.

**Comment by marcreichel** [comment]
@HDVinnie Well, then: Here we go 🎉

**Comment by marcreichel** [comment]
@HDVinnie Version 3.6.0 is released 👍🏼 Let me know if everything works as expected or if you run into any issues 🙂

**Pull request merged**
